"""Added Owner, Breed, Toy, and Dog model

Revision ID: 48b912f1f492
Revises: b4a0a4b5c197
Create Date: 2023-07-19 12:59:38.877359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b912f1f492'
down_revision = 'b4a0a4b5c197'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hair_length', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('broken', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('checked_in', sa.Boolean(), nullable=True),
    sa.Column('days_checked_in', sa.Integer(), nullable=True),
    sa.Column('temperament', sa.String(), nullable=True),
    sa.Column('toy_id', sa.Integer(), nullable=True),
    sa.Column('breed_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], name=op.f('fk_dogs_breed_id_breeds')),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_dogs_owner_id_owners')),
    sa.ForeignKeyConstraint(['toy_id'], ['toys.id'], name=op.f('fk_dogs_toy_id_toys')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dogs')
    op.drop_table('toys')
    op.drop_table('owners')
    op.drop_table('breeds')
    # ### end Alembic commands ###
